import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
const root = path.resolve(import.meta.dirname, '..');
const persistence = fs.readFileSync(path.join(root, 'src/app/services/persistence.ts'), 'utf8');
const etna = fs.readFileSync(path.join(root, 'src/app/services/etnaRegistry.ts'), 'utf8');
const app = fs.readFileSync(path.join(root, 'src/app/App.tsx'), 'utf8');
const ws = fs.readFileSync(path.resolve(root, '../vulcan/ws_general.py'), 'utf8');
const server = fs.readFileSync(path.resolve(root, '../vulcan/server.py'), 'utf8');
assert.match(persistence, /const PROVIDERS_KEY = 'vulcan:providers'/);
assert.match(persistence, /scopedNetworkKey\(PROVIDERS_KEY\)/);
assert.match(persistence, /migrateScopedNetworkValue\(PROVIDERS_KEY\)/);
assert.doesNotMatch(persistence, /generalWS\.send\('providers\/save'/);
assert.match(etna, /const SERVERS_KEY = 'vulcan:etna_servers'/);
assert.match(etna, /scopedNetworkKey\(SERVERS_KEY\)/);
assert.match(etna, /migrateScopedNetworkValue\(SERVERS_KEY\)/);
assert.match(app, /scoped by Vulcan[\s\S]*endpoint/);
const routes = ws.match(/def _routes[\s\S]*?async def _ping/)?.[0] || '';
assert.doesNotMatch(routes, /providers\/save|providers\/list|providers\/current|etna\/servers\/save|etna\/refresh|etna\/route|etna\/state/);
assert.match(routes, /network\/http-json/);
assert.match(server, /config\.client_owned_network/);
assert.match(server, /stale = \("providers", "inference", "etna_servers", "etna_routes"\)/);
assert.doesNotMatch(ws, /cfg\.save\(|config\["providers"\]|config\["etna_servers"\]/);
console.log('Client-owned network configuration regression: ok');
