import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
const root = path.resolve(import.meta.dirname, '..');
const settings = fs.readFileSync(path.join(root, 'src/app/components/SettingsDialog.tsx'), 'utf8');
const app = fs.readFileSync(path.join(root, 'src/app/App.tsx'), 'utf8');
const clientRegistry = fs.readFileSync(path.join(root, 'src/app/services/etnaRegistry.ts'), 'utf8');
const runtime = fs.readFileSync(path.resolve(root, '../vulcan/agent_runtime.py'), 'utf8');
const ws = fs.readFileSync(path.resolve(root, '../vulcan/ws_general.py'), 'utf8');
assert.match(clientRegistry, /sameLogicalKit/);
assert.match(clientRegistry, /a\.tools\.length !== b\.tools\.length/);
assert.match(clientRegistry, /unresolved_conflict/);
assert.match(clientRegistry, /selected_server_id/);
assert.match(clientRegistry, /last-known inventory/i);
assert.match(clientRegistry, /vulcan:etna_servers/);
assert.match(clientRegistry, /name: 'Local'/);
assert.match(clientRegistry, /networkPointOfView: 'client'/);
assert.match(clientRegistry, /network\/http-json/);
assert.match(ws, /client\/register/);
assert.match(ws, /network\/http-json/);
assert.doesNotMatch(ws.match(/def _routes[\s\S]*?async def _ping/)?.[0] || '', /etna\/servers\/save|etna\/refresh|etna\/route|etna\/state/);
assert.match(runtime, /effective_source/);
assert.match(runtime, /etna_registry\.relay_json/);
assert.match(app, /refreshEtnaState/);
assert.match(app, /push\/etna-http-request/);
assert.match(settings, /Conflicts found, resolve in the Kits tab/);
assert.match(settings, /Select server\.\.\./);
assert.match(settings, /Servers:/);
assert.match(settings, /Kits:/);
assert.match(settings, /Tools:/);
assert.doesNotMatch(settings, /Kits, Tools:/);
assert.match(settings, /row-span-4/);
assert.match(settings, /Connections:/);
assert.match(settings, /Based on the number of Etna servers with a healthy connection/);
console.log('Etna multi-server regression: ok');
